# Exploring and Cleaning Player Team Data

In this notebook, we will be exploring and preparing a dataset containing player statistics from various teams. The overall goal is to clean and organize this data in a way that allows us to efficiently analyze and work with team-specific information.

### Step 1: Checking for Missing Values in Team Names

Our first step is to verify the integrity of the dataset by checking for any missing or undefined values in the `Basic Info_Team Name` column. Missing team names could indicate incomplete or faulty data, which could affect subsequent analysis. If any NaN values are found, we will either correct or remove them to ensure that the data is clean before proceeding with further analysis.

In [1]:
import numpy as np
import pandas as pd
import re 

# Read the data from the CSV file
df = pd.read_csv('../data/deep_player_data.csv')

In [2]:
# Filter the DataFrame (teams with missing or undefined team names)
filtered_df = df[df['Basic Info_Team Name'].isna() | (df['Basic Info_Team Name'] == 'undefined')]

# Select only the player name and team name columns
filtered_df_selected = filtered_df[['Basic Info_Player Name', 'Basic Info_Team Name']]

# Display the selected data
display(filtered_df_selected.head())
display(filtered_df_selected.tail())

    Basic Info_Player Name Basic Info_Team Name
139                 CLASIA            undefined
324                   motm            undefined
562                   chop            undefined
580                stamina            undefined

    Basic Info_Player Name Basic Info_Team Name
139                 CLASIA            undefined
324                   motm            undefined
562                   chop            undefined
580                stamina            undefined

In [3]:
# Get the count of rows in the filtered DataFrame
row_count = filtered_df_selected.shape[0]

# Display the row count
print(f'The number of players/teams in the filtered data: {row_count}')

The number of players/teams in the filtered data: 4

In [4]:
#Checking the original data frame
df_selected = df[['Basic Info_Player Name', 'Basic Info_Team Name']]
display(df_selected.head())

  Basic Info_Player Name Basic Info_Team Name
0                  ZywOo             Vitality
1                 s1mple        Natus Vincere
2                  sh1ro               Spirit
3                   donk               Spirit
4                   deko               Aurora

In [5]:
# Check the data types of the selected columns
team_name_dtype = df['Basic Info_Team Name'].dtype

# Check for NaN values in the 'Basic Info_Team Name' column and count occurrences of each type (NaN or not NaN)
team_name_nan_count = df['Basic Info_Team Name'].isna().sum()
team_name_non_nan_count = df['Basic Info_Team Name'].notna().sum()

# Display the results
print(f"Data type of 'Basic Info_Team Name': {team_name_dtype}")
print(f"Number of NaN values: {team_name_nan_count}")
print(f"Number of non-NaN values: {team_name_non_nan_count}")

Data type of 'Basic Info_Team Name': object
Number of NaN values: 0
Number of non-NaN values: 968

In [6]:
# Get unique values in the 'Basic Info_Team Name' column
unique_teams = df['Basic Info_Team Name'].unique()

# Count occurrences of each unique value
team_counts = df['Basic Info_Team Name'].value_counts(dropna=False)

# Display unique values and their counts
print("Unique team names and their counts:")
print(team_counts)

# Check for empty strings or whitespace-only entries
empty_entries = df[df['Basic Info_Team Name'].str.strip() == '']
print(f"\nNumber of empty or whitespace-only entries: {len(empty_entries)}")

# Check for entries that might indicate no team
no_team_entries = df[df['Basic Info_Team Name'].str.lower().isin(['no team', 'none', 'n/a', 'unknown'])]
print(f"\nNumber of entries potentially indicating no team: {len(no_team_entries)}")

# Check for unusually short team names (less than 2 characters)
short_names = df[df['Basic Info_Team Name'].str.len() < 2]
print(f"\nNumber of unusually short team names: {len(short_names)}")

# Display any unusual entries for manual inspection
print("\nUnusual entries (if any):")
unusual_entries = team_counts[team_counts < 5]
print(unusual_entries)

Unique team names and their counts:
Basic Info_Team Name
No team              383
Ninjas in Pyjamas      8
OG                     7
G2                     7
Into the Breach        7
                    ...
Arcade                 1
MASONIC                1
ENCE Academy           1
Punishers              1
MIBR Academy           1
Name: count, Length: 185, dtype: int64

Number of empty or whitespace-only entries: 0

Number of entries potentially indicating no team: 383

Number of unusually short team names: 0

Unusual entries (if any):
Basic Info_Team Name
ESC             4
TSM             4
KRÜ             4
undefined       4
Liquid          4
               ..
Arcade          1
MASONIC         1
ENCE Academy    1
Punishers       1
MIBR Academy    1
Name: count, Length: 133, dtype: int64

### Step 2: Cleaning the Data

After confirming that no missing values (NaN) are present in the `Basic Info_Team Name` column only solo players listed under no team, we can move forward with cleaning and preparing the dataset. This involves handling outliers, normalizing numerical values, and ensuring that all columns are formatted consistently. 

We aim to normalize the player statistics across all teams to ensure consistent comparisons and analysis. Once the data is cleaned, we will split it into separate dataframes for each team, allowing us to analyze team-specific information more efficiently.

In [7]:
#Checking the original data frame data types
display(df.dtypes)

# Count the number of columns with each data type
type_counts = df.dtypes.value_counts()
print(type_counts)

Summary Stats_DPR                               float64
Summary Stats_KPR                               float64
Detailed Stats_Deaths / round                   float64
Role Stats_Firepower_Score                       object
Role Stats_Opening_Win% after opening kill       object
                                                 ...
Detailed Stats_Maps played                        int64
Role Stats_Trading_Saved teammate per round     float64
Summary Stats_Rating 2.0                        float64
Role Stats_Opening_Score                         object
Role Stats_Entrying_Traded deaths percentage     object
Length: 74, dtype: object

float64    37
object     32
int64       5
Name: count, dtype: int64

In [8]:
type_dict = {str(t): df.select_dtypes(include=[t]).columns.tolist() for t in df.dtypes.unique()}
for t, cols in type_dict.items():
    print(f"\n{t}:")
    print(", ".join(cols))

float64:
Summary Stats_DPR, Summary Stats_KPR, Detailed Stats_Deaths / round, Detailed Stats_Damage / Round, Role Stats_Opening_Opening deaths per round, Detailed Stats_Assists / round, Role Stats_Sniping_Sniper kills per round, Role Stats_Opening_Opening kills per round, Role Stats_Sniping_Sniper multi-kill rounds, Detailed Stats_Kills / round, Detailed Stats_Rating 1.0, Detailed Stats_Rating 2.0, Role Stats_Clutching_Clutch points per round, Role Stats_Entrying_Saved by teammate per round, Role Stats_Utility_Utility kills per 100 rounds, Summary Stats_Impact, Role Stats_Utility_Flashes thrown per round, Role Stats_Firepower_Kills per round, Detailed Stats_Saved by teammate / round, Role Stats_Entrying_Traded deaths per round, Role Stats_Entrying_Assists per round, Role Stats_Trading_Trade kills per round, Role Stats_Utility_Flash assists per round, Role Stats_Utility_Time opponent flashed per round, Summary Stats_Rating 1.0, Summary Stats_ADR, Role Stats_Utility_Utility damage per round, Detailed Stats_Saved teammates / round, Role Stats_Firepower_Damage per round, Detailed Stats_K/D Ratio, Role Stats_Firepower_Kills per round win, Role Stats_Opening_Attacks per round, Role Stats_Firepower_Damage per round win, Role Stats_Sniping_Sniper opening kills per round, Detailed Stats_Grenade dmg / Round, Role Stats_Trading_Saved teammate per round, Summary Stats_Rating 2.0

object:
Role Stats_Firepower_Score, Role Stats_Opening_Win% after opening kill, Role Stats_Clutching_Score, Detailed Stats_Headshot %, Role Stats_Entrying_Support rounds, Basic Info_Team Name, Role Stats_Sniping_Rounds with sniper kills percentage, URL, Role Stats_Firepower_Rating 2.0, Role Stats_Opening_Opening success, Role Stats_Firepower_Rounds with a kill, Role Stats_Firepower_Rounds with a multi-kill, Role Stats_Entrying_Score, Basic Info_Age, Role Stats_Trading_Trade kills percentage, Role Stats_Clutching_Saves per round loss, Role Stats_Trading_Score, Role Stats_Entrying_Opening deaths traded percentage, Summary Stats_KAST, Role Stats_Trading_Assisted kills percentage, Basic Info_Real Name, Role Stats_Clutching_1on1 win percentage, Role Stats_Firepower_Pistol round rating, Role Stats_Sniping_Sniper kills percentage, Role Stats_Sniping_Score, Basic Info_Player Name, Role Stats_Opening_Opening attempts, Role Stats_Utility_Score, Role Stats_Clutching_Time alive per round, Role Stats_Clutching_Last alive percentage, Role Stats_Opening_Score, Role Stats_Entrying_Traded deaths percentage

int64:
Detailed Stats_Total kills, Detailed Stats_Total deaths, Role Stats_Trading_Damage per kill, Detailed Stats_Rounds played, Detailed Stats_Maps played

In [9]:
# Check the number of unique values in each object column
for col in df.select_dtypes(include=['object']):
    print(f"\nColumn: {col}")
    print(df[col].head()) 
    print(df[col].nunique(), "unique values")

Column: Role Stats_Firepower_Score
0    98/100
1    97/100
2    85/100
3    98/100
4    89/100
Name: Role Stats_Firepower_Score, dtype: object
87 unique values

Column: Role Stats_Opening_Win% after opening kill
0    74.5%
1    75.6%
2    77.3%
3    73.8%
4    73.2%
Name: Role Stats_Opening_Win% after opening kill, dtype: object
111 unique values

Column: Role Stats_Clutching_Score
0    75/100
1    52/100
2    83/100
3    37/100
4    73/100
Name: Role Stats_Clutching_Score, dtype: object
59 unique values

Column: Detailed Stats_Headshot %
0    41.3%
1    41.1%
2    28.9%
3    60.6%
4    38.3%
Name: Detailed Stats_Headshot %, dtype: object
327 unique values

Column: Role Stats_Entrying_Support rounds
0    15.3%
1    10.5%
2    19.4%
3    12.4%
4    16.3%
Name: Role Stats_Entrying_Support rounds, dtype: object
134 unique values

Column: Basic Info_Team Name
0         Vitality
1    Natus Vincere
2           Spirit
3           Spirit
4           Aurora
Name: Basic Info_Team Name, dtype: object
185 unique values

Column: Role Stats_Sniping_Rounds with sniper kills percentage
0    14.7%
1    15.5%
2    24.6%
3     0.9%
4    16.5%
Name: Role Stats_Sniping_Rounds with sniper kills percentage, dtype: object
181 unique values

Column: URL
0    https://www.hltv.org/stats/players/11893/zywoo
1    https://www.hltv.org/stats/players/7998/s1mple
2    https://www.hltv.org/stats/players/16920/sh1ro
3     https://www.hltv.org/stats/players/21167/donk
4     https://www.hltv.org/stats/players/20113/deko
Name: URL, dtype: object
968 unique values

Column: Role Stats_Firepower_Rating 2.0
0    1.29
1       -
2    1.22
3    1.28
4    1.17
Name: Role Stats_Firepower_Rating 2.0, dtype: object
39 unique values

Column: Role Stats_Opening_Opening success
0    54.6%
1    55.3%
2    59.5%
3    51.4%
4    56.3%
Name: Role Stats_Opening_Opening success, dtype: object
187 unique values

Column: Role Stats_Firepower_Rounds with a kill
0    50.1%
1    51.8%
2    48.8%
3    51.9%
4    49.2%
Name: Role Stats_Firepower_Rounds with a kill, dtype: object
118 unique values

Column: Role Stats_Firepower_Rounds with a multi-kill
0    20.0%
1    21.0%
2    17.4%
3    21.6%
4    18.1%
Name: Role Stats_Firepower_Rounds with a multi-kill, dtype: object
92 unique values

Column: Role Stats_Entrying_Score
0    43/100
1     6/100
2    15/100
3    63/100
4    17/100
Name: Role Stats_Entrying_Score, dtype: object
89 unique values

Column: Basic Info_Age
0    23 years
1    26 years
2    23 years
3    17 years
4    23 years
Name: Basic Info_Age, dtype: object
23 unique values

Column: Role Stats_Trading_Trade kills percentage
0    23.8%
1    17.6%
2    25.8%
3    24.2%
4    23.9%
Name: Role Stats_Trading_Trade kills percentage, dtype: object
174 unique values

Column: Role Stats_Clutching_Saves per round loss
0    2.0%
1    3.8%
2    8.9%
3    2.6%
4    5.9%
Name: Role Stats_Clutching_Saves per round loss, dtype: object
65 unique values

Column: Role Stats_Trading_Score
0    54/100
1    26/100
2    60/100
3    70/100
4    51/100
Name: Role Stats_Trading_Score, dtype: object
75 unique values

Column: Role Stats_Entrying_Opening deaths traded percentage
0    30.3%
1    13.5%
2    23.7%
3    27.0%
4    24.5%
Name: Role Stats_Entrying_Opening deaths traded percentage, dtype: object
230 unique values

Column: Summary Stats_KAST
0    75.4%
1    73.9%
2    76.3%
3    74.1%
4    74.7%
Name: Summary Stats_KAST, dtype: object
98 unique values

Column: Role Stats_Trading_Assisted kills percentage
0    16.1%
1     8.1%
2    10.0%
3    18.1%
4     7.7%
Name: Role Stats_Trading_Assisted kills percentage, dtype: object
228 unique values

Column: Basic Info_Real Name
0        Mathieu Herbaut
1    Oleksandr Kostyliev
2         Dmitry Sokolov
3      Danil Kryshkovets
4           Denis Zhukov
Name: Basic Info_Real Name, dtype: object
968 unique values

Column: Role Stats_Clutching_1on1 win percentage
0    77.4%
1    70.6%
2    74.2%
3    75.0%
4    68.6%
Name: Role Stats_Clutching_1on1 win percentage, dtype: object
220 unique values

Column: Role Stats_Firepower_Pistol round rating
0    1.42
1       -
2    1.33
3    1.42
4    1.23
Name: Role Stats_Firepower_Pistol round rating, dtype: object
60 unique values

Column: Role Stats_Sniping_Sniper kills percentage
0    26.9%
1    28.8%
2    46.7%
3     1.5%
4    31.5%
Name: Role Stats_Sniping_Sniper kills percentage, dtype: object
238 unique values

Column: Role Stats_Sniping_Score
0    86/100
1    87/100
2    93/100
3     1/100
4    91/100
Name: Role Stats_Sniping_Score, dtype: object
71 unique values

Column: Basic Info_Player Name
0     ZywOo
1    s1mple
2     sh1ro
3      donk
4      deko
Name: Basic Info_Player Name, dtype: object
966 unique values

Column: Role Stats_Opening_Opening attempts
0    22.3%
1    20.2%
2    13.1%
3    27.2%
4    12.9%
Name: Role Stats_Opening_Opening attempts, dtype: object
176 unique values

Column: Role Stats_Utility_Score
0    61/100
1    37/100
2    66/100
3    28/100
4    58/100
Name: Role Stats_Utility_Score, dtype: object
84 unique values

Column: Role Stats_Clutching_Time alive per round
0    1m 10s
1    0m 59s
2    1m 19s
3     1m 6s
4    1m 20s
Name: Role Stats_Clutching_Time alive per round, dtype: object
89 unique values

Column: Role Stats_Clutching_Last alive percentage
0    12.5%
1    12.4%
2    17.8%
3     6.9%
4    17.1%
Name: Role Stats_Clutching_Last alive percentage, dtype: object
141 unique values

Column: Role Stats_Opening_Score
0    89/100
1    87/100
2    60/100
3    86/100
4    54/100
Name: Role Stats_Opening_Score, dtype: object
78 unique values

Column: Role Stats_Entrying_Traded deaths percentage
0    22.5%
1    13.5%
2    17.8%
3    22.9%
4    18.4%
Name: Role Stats_Entrying_Traded deaths percentage, dtype: object
169 unique values

In [10]:
def check_problematic_values(df, columns_to_check):
    results = {}
    for col in columns_to_check:
        if col in df.columns:
            total_count = len(df[col])
            nan_count = df[col].isna().sum()
            dash_count = (df[col] == '-').sum()
            other_count = total_count - nan_count - dash_count
            
            results[col] = {
                'NaN count': nan_count,
                'NaN percentage': (nan_count / total_count) * 100,
                '"-" count': dash_count,
                '"-" percentage': (dash_count / total_count) * 100,
                'Other values count': other_count,
                'Other values percentage': (other_count / total_count) * 100
            }
        else:
            results[col] = "Column not found in dataframe"
    
    return results

# List of columns to check
columns_to_check = [
    'Detailed Stats_Rating 1.0',
    'Summary Stats_Rating 1.0',
    'Detailed Stats_Rating 2.0',
    'Role Stats_Firepower_Rating 2.0',
    'Summary Stats_Rating 2.0',
    'Role Stats_Firepower_Pistol round rating',
    'Basic Info_Age'
]

# Run the check
results = check_problematic_values(df, columns_to_check)

# Display results
for col, data in results.items():
    print(f"\nColumn: {col}")
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, float):
                print(f"  {key}: {value:.2f}")
            else:
                print(f"  {key}: {value}")
    else:
        print(f"  {data}")

Column: Detailed Stats_Rating 1.0
  NaN count: 556
  NaN percentage: 57.44
  "-" count: 0
  "-" percentage: 0.00
  Other values count: 412
  Other values percentage: 42.56

Column: Summary Stats_Rating 1.0
  NaN count: 556
  NaN percentage: 57.44
  "-" count: 0
  "-" percentage: 0.00
  Other values count: 412
  Other values percentage: 42.56

Column: Detailed Stats_Rating 2.0
  NaN count: 412
  NaN percentage: 42.56
  "-" count: 0
  "-" percentage: 0.00
  Other values count: 556
  Other values percentage: 57.44

Column: Role Stats_Firepower_Rating 2.0
  NaN count: 0
  NaN percentage: 0.00
  "-" count: 412
  "-" percentage: 42.56
  Other values count: 556
  Other values percentage: 57.44

Column: Summary Stats_Rating 2.0
  NaN count: 412
  NaN percentage: 42.56
  "-" count: 0
  "-" percentage: 0.00
  Other values count: 556
  Other values percentage: 57.44

Column: Role Stats_Firepower_Pistol round rating
  NaN count: 0
  NaN percentage: 0.00
  "-" count: 412
  "-" percentage: 42.56
  Other values count: 556
  Other values percentage: 57.44

Column: Basic Info_Age
  NaN count: 0
  NaN percentage: 0.00
  "-" count: 0
  "-" percentage: 0.00
  Other values count: 968
  Other values percentage: 100.00

In [11]:
# Display a few rows of these columns for visual inspection
print("\nSample data:")
print(df[columns_to_check].head())

Sample data:
   Detailed Stats_Rating 1.0  Summary Stats_Rating 1.0  \
0                        NaN                       NaN
1                       1.24                      1.24
2                        NaN                       NaN
3                        NaN                       NaN
4                        NaN                       NaN

   Detailed Stats_Rating 2.0 Role Stats_Firepower_Rating 2.0  \
0                       1.32                            1.29
1                        NaN                               -
2                       1.25                            1.22
3                       1.27                            1.28
4                       1.22                            1.17

   Summary Stats_Rating 2.0 Role Stats_Firepower_Pistol round rating  \
0                      1.32                                     1.42
1                       NaN                                        -
2                      1.25                                     1.33
3                      1.27                                     1.42
4                      1.22                                     1.23

  Basic Info_Age
0       23 years
1       26 years
2       23 years
3       17 years
4       23 years

In [12]:
# Drop the URL column
df = df.drop('URL', axis=1)
print("URL column has been dropped.")

URL column has been dropped.

In [13]:
# Handle strange age data
anomalous_age_row = df[df['Basic Info_Age'].astype(str).str.contains('years')]

if not anomalous_age_row.empty:
    # Extract the correct age from the anomalous entry
    anomalous_age = anomalous_age_row['Basic Info_Age'].iloc[0]
    correct_age = int(re.search(r'(\d+) years', str(anomalous_age)).group(1))
    
    # Update the age for this specific row
    df.loc[anomalous_age_row.index, 'Basic Info_Age'] = correct_age
    
    print(f"Updated age for player: {anomalous_age_row['Basic Info_Player Name'].iloc[0]}")
    print(f"Old value: {anomalous_age}")
    print(f"New value: {correct_age}")
else:
    print("No anomalous age entry found.")

# Verify the change
print("\nAge column summary after update:")
print(df['Basic Info_Age'].describe())

print("\nCheck for any remaining non-numeric values in the Age column:")
non_numeric_ages = df[pd.to_numeric(df['Basic Info_Age'], errors='coerce').isna()]
if non_numeric_ages.empty:
    print("No non-numeric values found in the Age column.")
else:
    print("Rows with non-numeric ages:")
    print(non_numeric_ages[['Basic Info_Player Name', 'Basic Info_Age']])

Updated age for player: ZywOo
Old value: 23 years
New value: 23

Age column summary after update:
count     968
unique      1
top        23
freq      968
Name: Basic Info_Age, dtype: int64

Check for any remaining non-numeric values in the Age column:
No non-numeric values found in the Age column.

In [14]:
def is_numeric_column(series):
    numeric_sample = series.dropna().sample(min(len(series), 100))
    return all(isinstance(x, str) and (
        ('/' in x) or 
        (x.replace('.', '').replace('-', '').isdigit()) or 
        (x.rstrip('%').replace('.', '').replace('-', '').isdigit()) or
        (x.split()[0].replace('.', '').replace('-', '').isdigit()) or  # For handling "23 years" format
        x.strip() == '-'  # Handle lone dash
    ) for x in numeric_sample)

def convert_to_numeric(value):
    if isinstance(value, str):
        value = value.strip()
        if '/' in value:
            numerator, denominator = value.split('/')
            return float(numerator) / float(denominator)
        elif value.endswith('%'):
            return float(value.rstrip('%')) / 100
        elif value.endswith('years'):
            return float(value.split()[0])
        elif value == '-':
            return np.nan
        else:
            try:
                return float(value)
            except ValueError:
                return np.nan
    return value

def process_dataframe(df):
    object_columns = df.select_dtypes(include=['object']).columns
    
    for col in object_columns:
        if is_numeric_column(df[col]) or 'Rating' in col or col == 'Basic Info_Age':
            print(f"Converting column: {col}")
            df[col] = df[col].apply(convert_to_numeric)
        else:
            print(f"Skipping non-numeric column: {col}")
    
    return df

def display_column_info(df):
    for col in df.columns:
        print(f"\nColumn: {col}")
        print(f"Data type: {df[col].dtype}")
        print(df[col].head())
        if df[col].dtype != 'object':
            print(f"Min value: {df[col].min()}, Max value: {df[col].max()}")
        print(f"Unique values: {df[col].nunique()}")

In [15]:
# Usage
df = process_dataframe(df)
display_column_info(df)

Converting column: Role Stats_Firepower_Score
Converting column: Role Stats_Opening_Win% after opening kill
Converting column: Role Stats_Clutching_Score
Converting column: Detailed Stats_Headshot %
Converting column: Role Stats_Entrying_Support rounds
Skipping non-numeric column: Basic Info_Team Name
Converting column: Role Stats_Sniping_Rounds with sniper kills percentage
Converting column: Role Stats_Firepower_Rating 2.0
Converting column: Role Stats_Opening_Opening success
Converting column: Role Stats_Firepower_Rounds with a kill
Converting column: Role Stats_Firepower_Rounds with a multi-kill
Converting column: Role Stats_Entrying_Score
Converting column: Basic Info_Age
Converting column: Role Stats_Trading_Trade kills percentage
Converting column: Role Stats_Clutching_Saves per round loss
Converting column: Role Stats_Trading_Score
Converting column: Role Stats_Entrying_Opening deaths traded percentage
Converting column: Summary Stats_KAST
Converting column: Role Stats_Trading_Assisted kills percentage
Skipping non-numeric column: Basic Info_Real Name
Converting column: Role Stats_Clutching_1on1 win percentage
Converting column: Role Stats_Firepower_Pistol round rating
Converting column: Role Stats_Sniping_Sniper kills percentage
Converting column: Role Stats_Sniping_Score
Skipping non-numeric column: Basic Info_Player Name
Converting column: Role Stats_Opening_Opening attempts
Converting column: Role Stats_Utility_Score
Skipping non-numeric column: Role Stats_Clutching_Time alive per round
Converting column: Role Stats_Clutching_Last alive percentage
Converting column: Role Stats_Opening_Score
Converting column: Role Stats_Entrying_Traded deaths percentage

Column: Summary Stats_DPR
Data type: float64
0    0.61
1    0.63
2    0.54
3    0.67
4    0.59
Name: Summary Stats_DPR, dtype: float64
Min value: 0.54, Max value: 0.75
Unique values: 21

Column: Summary Stats_KPR
Data type: float64
0    0.84
1    0.85
2    0.77
3    0.84
4    0.79
Name: Summary Stats_KPR, dtype: float64
Min value: 0.55, Max value: 0.85
Unique values: 28

Column: Detailed Stats_Deaths / round
Data type: float64
0    0.61
1    0.63
2    0.54
3    0.67
4    0.59
Name: Detailed Stats_Deaths / round, dtype: float64
Min value: 0.54, Max value: 0.75
Unique values: 21

Column: Role Stats_Firepower_Score
Data type: float64
0    0.98
1    0.97
2    0.85
3    0.98
4    0.89
Name: Role Stats_Firepower_Score, dtype: float64
Min value: 0.08, Max value: 0.98
Unique values: 87

Column: Role Stats_Opening_Win% after opening kill
Data type: float64
0    0.745
1    0.756
2    0.773
3    0.738
4    0.732
Name: Role Stats_Opening_Win% after opening kill, dtype: float64
Min value: 0.652, Max value: 0.8140000000000001
Unique values: 111

Column: Role Stats_Clutching_Score
Data type: float64
0    0.75
1    0.52
2    0.83
3    0.37
4    0.73
Name: Role Stats_Clutching_Score, dtype: float64
Min value: 0.19, Max value: 0.83
Unique values: 59

Column: Detailed Stats_Damage / Round
Data type: float64
0    87.3
1    85.4
2    78.3
3    88.3
4    79.8
Name: Detailed Stats_Damage / Round, dtype: float64
Min value: 61.3, Max value: 91.7
Unique values: 185

Column: Detailed Stats_Headshot %
Data type: float64
0    0.413
1    0.411
2    0.289
3    0.606
4    0.383
Name: Detailed Stats_Headshot %, dtype: float64
Min value: 0.23600000000000002, Max value: 0.6809999999999999
Unique values: 327

Column: Role Stats_Opening_Opening deaths per round
Data type: float64
0    0.10
1    0.09
2    0.05
3    0.13
4    0.05
Name: Role Stats_Opening_Opening deaths per round, dtype: float64
Min value: 0.04, Max value: 0.19
Unique values: 16

Column: Role Stats_Entrying_Support rounds
Data type: float64
0    0.153
1    0.105
2    0.194
3    0.124
4    0.163
Name: Role Stats_Entrying_Support rounds, dtype: float64
Min value: 0.0, Max value: 0.218
Unique values: 134

Column: Basic Info_Team Name
Data type: object
0         Vitality
1    Natus Vincere
2           Spirit
3           Spirit
4           Aurora
Name: Basic Info_Team Name, dtype: object
Unique values: 185

Column: Role Stats_Sniping_Rounds with sniper kills percentage
Data type: float64
0    0.147
1    0.155
2    0.246
3    0.009
4    0.165
Name: Role Stats_Sniping_Rounds with sniper kills percentage, dtype: float64
Min value: 0.0, Max value: 0.29100000000000004
Unique values: 181

Column: Detailed Stats_Assists / round
Data type: float64
0    0.13
1    0.10
2    0.11
3    0.15
4    0.12
Name: Detailed Stats_Assists / round, dtype: float64
Min value: 0.08, Max value: 0.19
Unique values: 12

Column: Role Stats_Sniping_Sniper kills per round
Data type: float64
0    0.21
1    0.18
2    0.34
3    0.01
4    0.23
Name: Role Stats_Sniping_Sniper kills per round, dtype: float64
Min value: 0.0, Max value: 0.41
Unique values: 41

Column: Role Stats_Opening_Opening kills per round
Data type: float64
0    0.12
1    0.11
2    0.07
3    0.13
4    0.07
Name: Role Stats_Opening_Opening kills per round, dtype: float64
Min value: 0.04, Max value: 0.15
Unique values: 12

Column: Role Stats_Sniping_Sniper multi-kill rounds
Data type: float64
0    0.040
1    0.050
2    0.070
3    0.003
4    0.050
Name: Role Stats_Sniping_Sniper multi-kill rounds, dtype: float64
Min value: 0.0, Max value: 0.09
Unique values: 28

Column: Detailed Stats_Kills / round
Data type: float64
0    0.84
1    0.85
2    0.77
3    0.84
4    0.79
Name: Detailed Stats_Kills / round, dtype: float64
Min value: 0.55, Max value: 0.85
Unique values: 28

Column: Detailed Stats_Rating 1.0
Data type: float64
0     NaN
1    1.24
2     NaN
3     NaN
4     NaN
Name: Detailed Stats_Rating 1.0, dtype: float64
Min value: 0.81, Max value: 1.24
Unique values: 34

Column: Role Stats_Firepower_Rating 2.0
Data type: float64
0    1.29
1     NaN
2    1.22
3    1.28
4    1.17
Name: Role Stats_Firepower_Rating 2.0, dtype: float64
Min value: 0.86, Max value: 1.29
Unique values: 38

Column: Role Stats_Opening_Opening success
Data type: float64
0    0.546
1    0.553
2    0.595
3    0.514
4    0.563
Name: Role Stats_Opening_Opening success, dtype: float64
Min value: 0.33299999999999996, Max value: 0.632
Unique values: 187

Column: Detailed Stats_Total kills
Data type: int64
0    29136
1    38714
2    23994
3     9768
4    18625
Name: Detailed Stats_Total kills, dtype: int64
Min value: 6563, Max value: 48720
Unique values: 945

Column: Role Stats_Firepower_Rounds with a kill
Data type: float64
0    0.501
1    0.518
2    0.488
3    0.519
4    0.492
Name: Role Stats_Firepower_Rounds with a kill, dtype: float64
Min value: 0.36700000000000005, Max value: 0.519
Unique values: 118

Column: Detailed Stats_Rating 2.0
Data type: float64
0    1.32
1     NaN
2    1.25
3    1.27
4    1.22
Name: Detailed Stats_Rating 2.0, dtype: float64
Min value: 0.9, Max value: 1.32
Unique values: 37

Column: Role Stats_Firepower_Rounds with a multi-kill
Data type: float64
0    0.200
1    0.210
2    0.174
3    0.216
4    0.181
Name: Role Stats_Firepower_Rounds with a multi-kill, dtype: float64
Min value: 0.102, Max value: 0.21600000000000003
Unique values: 92

Column: Detailed Stats_Total deaths
Data type: int64
0    21011
1    29045
2    16664
3     7789
4    13886
Name: Detailed Stats_Total deaths, dtype: int64
Min value: 6779, Max value: 46241
Unique values: 950

Column: Role Stats_Entrying_Score
Data type: float64
0    0.43
1    0.06
2    0.15
3    0.63
4    0.17
Name: Role Stats_Entrying_Score, dtype: float64
Min value: 0.0, Max value: 0.9
Unique values: 89

Column: Role Stats_Clutching_Clutch points per round
Data type: float64
0    0.04
1    0.03
2    0.04
3    0.01
4    0.03
Name: Role Stats_Clutching_Clutch points per round, dtype: float64
Min value: 0.0, Max value: 0.04
Unique values: 5

Column: Basic Info_Age
Data type: int64
0    23
1    23
2    23
3    23
4    23
Name: Basic Info_Age, dtype: int64
Min value: 23, Max value: 23
Unique values: 1

Column: Role Stats_Trading_Trade kills percentage
Data type: float64
0    0.238
1    0.176
2    0.258
3    0.242
4    0.239
Name: Role Stats_Trading_Trade kills percentage, dtype: float64
Min value: 0.001, Max value: 0.305
Unique values: 174

Column: Role Stats_Clutching_Saves per round loss
Data type: float64
0    0.020
1    0.038
2    0.089
3    0.026
4    0.059
Name: Role Stats_Clutching_Saves per round loss, dtype: float64
Min value: 0.004, Max value: 0.10099999999999999
Unique values: 65

Column: Role Stats_Entrying_Saved by teammate per round
Data type: float64
0    0.11
1    0.07
2    0.09
3    0.12
4    0.10
Name: Role Stats_Entrying_Saved by teammate per round, dtype: float64
Min value: 0.0, Max value: 0.16
Unique values: 16

Column: Role Stats_Trading_Score
Data type: float64
0    0.54
1    0.26
2    0.60
3    0.70
4    0.51
Name: Role Stats_Trading_Score, dtype: float64
Min value: 0.03, Max value: 0.83
Unique values: 75

Column: Role Stats_Utility_Utility kills per 100 rounds
Data type: float64
0    0.73
1    0.40
2    0.65
3    0.55
4    0.66
Name: Role Stats_Utility_Utility kills per 100 rounds, dtype: float64
Min value: 0.0, Max value: 1.54
Unique values: 113

Column: Summary Stats_Impact
Data type: float64
0    1.43
1    1.34
2    1.20
3    1.38
4    1.18
Name: Summary Stats_Impact, dtype: float64
Min value: 0.75, Max value: 1.43
Unique values: 56

Column: Role Stats_Entrying_Opening deaths traded percentage
Data type: float64
0    0.303
1    0.135
2    0.237
3    0.270
4    0.245
Name: Role Stats_Entrying_Opening deaths traded percentage, dtype: float64
Min value: 0.002, Max value: 0.397
Unique values: 230

Column: Role Stats_Utility_Flashes thrown per round
Data type: float64
0    0.81
1    0.73
2    0.86
3    0.43
4    0.77
Name: Role Stats_Utility_Flashes thrown per round, dtype: float64
Min value: 0.002, Max value: 1.24
Unique values: 101

Column: Summary Stats_KAST
Data type: float64
0    0.754
1    0.739
2    0.763
3    0.741
4    0.747
Name: Summary Stats_KAST, dtype: float64
Min value: 0.644, Max value: 0.763
Unique values: 98

Column: Role Stats_Firepower_Kills per round
Data type: float64
0    0.77
1    0.80
2    0.72
3    0.82
4    0.72
Name: Role Stats_Firepower_Kills per round, dtype: float64
Min value: 0.49, Max value: 0.82
Unique values: 30

Column: Role Stats_Trading_Assisted kills percentage
Data type: float64
0    0.161
1    0.081
2    0.100
3    0.181
4    0.077
Name: Role Stats_Trading_Assisted kills percentage, dtype: float64
Min value: -0.128, Max value: 0.259
Unique values: 228

Column: Detailed Stats_Saved by teammate / round
Data type: float64
0    0.09
1    0.08
2    0.08
3    0.11
4    0.08
Name: Detailed Stats_Saved by teammate / round, dtype: float64
Min value: 0.04, Max value: 0.14
Unique values: 10

Column: Role Stats_Entrying_Traded deaths per round
Data type: float64
0    0.15
1    0.09
2    0.10
3    0.16
4    0.12
Name: Role Stats_Entrying_Traded deaths per round, dtype: float64
Min value: 0.0, Max value: 0.21
Unique values: 20

Column: Role Stats_Entrying_Assists per round
Data type: float64
0    0.12
1    0.09
2    0.10
3    0.13
4    0.10
Name: Role Stats_Entrying_Assists per round, dtype: float64
Min value: 0.07, Max value: 0.17
Unique values: 11

Column: Role Stats_Trading_Trade kills per round
Data type: float64
0    0.18
1    0.14
2    0.18
3    0.20
4    0.17
Name: Role Stats_Trading_Trade kills per round, dtype: float64
Min value: 0.0005, Max value: 0.2
Unique values: 19

Column: Role Stats_Trading_Damage per kill
Data type: int64
0    106
1     80
2    103
3    104
4    103
Name: Role Stats_Trading_Damage per kill, dtype: int64
Min value: 0, Max value: 122
Unique values: 74

Column: Role Stats_Utility_Flash assists per round
Data type: float64
0    0.06
1    0.04
2    0.07
3    0.01
4    0.06
Name: Role Stats_Utility_Flash assists per round, dtype: float64
Min value: 0.0, Max value: 0.12
Unique values: 21

Column: Role Stats_Utility_Time opponent flashed per round
Data type: float64
0    2.12
1    1.96
2    2.26
3    1.69
4    2.27
Name: Role Stats_Utility_Time opponent flashed per round, dtype: float64
Min value: 0.02, Max value: 2.85
Unique values: 158

Column: Summary Stats_Rating 1.0
Data type: float64
0     NaN
1    1.24
2     NaN
3     NaN
4     NaN
Name: Summary Stats_Rating 1.0, dtype: float64
Min value: 0.81, Max value: 1.24
Unique values: 34

Column: Basic Info_Real Name
Data type: object
0        Mathieu Herbaut
1    Oleksandr Kostyliev
2         Dmitry Sokolov
3      Danil Kryshkovets
4           Denis Zhukov
Name: Basic Info_Real Name, dtype: object
Unique values: 968

Column: Summary Stats_ADR
Data type: float64
0    87.3
1    85.4
2    78.3
3    88.3
4    79.8
Name: Summary Stats_ADR, dtype: float64
Min value: 61.3, Max value: 91.7
Unique values: 185

Column: Role Stats_Clutching_1on1 win percentage
Data type: float64
0    0.774
1    0.706
2    0.742
3    0.750
4    0.686
Name: Role Stats_Clutching_1on1 win percentage, dtype: float64
Min value: 0.519, Max value: 0.865
Unique values: 220

Column: Role Stats_Utility_Utility damage per round
Data type: float64
0    2.58
1    1.74
2    2.75
3    2.78
4    2.69
Name: Role Stats_Utility_Utility damage per round, dtype: float64
Min value: 0.92, Max value: 10.13
Unique values: 325

Column: Role Stats_Firepower_Pistol round rating
Data type: float64
0    1.42
1     NaN
2    1.33
3    1.42
4    1.23
Name: Role Stats_Firepower_Pistol round rating, dtype: float64
Min value: 0.8, Max value: 1.42
Unique values: 59

Column: Detailed Stats_Saved teammates / round
Data type: float64
0    0.12
1    0.11
2    0.11
3    0.14
4    0.11
Name: Detailed Stats_Saved teammates / round, dtype: float64
Min value: 0.07, Max value: 0.16
Unique values: 9

Column: Role Stats_Firepower_Damage per round
Data type: float64
0    83.1
1    81.8
2    74.4
3    86.6
4    75.5
Name: Role Stats_Firepower_Damage per round, dtype: float64
Min value: 55.9, Max value: 108.6
Unique values: 201

Column: Detailed Stats_K/D Ratio
Data type: float64
0    1.39
1    1.33
2    1.44
3    1.25
4    1.34
Name: Detailed Stats_K/D Ratio, dtype: float64
Min value: 0.78, Max value: 1.44
Unique values: 56

Column: Role Stats_Sniping_Sniper kills percentage
Data type: float64
0    0.269
1    0.288
2    0.467
3    0.015
4    0.315
Name: Role Stats_Sniping_Sniper kills percentage, dtype: float64
Min value: 0.0, Max value: 0.632
Unique values: 238

Column: Role Stats_Firepower_Kills per round win
Data type: float64
0    1.06
1    1.09
2    0.92
3    1.14
4    0.96
Name: Role Stats_Firepower_Kills per round win, dtype: float64
Min value: 0.66, Max value: 1.14
Unique values: 43

Column: Role Stats_Opening_Attacks per round
Data type: float64
0    2.41
1    1.66
2    2.06
3    2.62
4    2.14
Name: Role Stats_Opening_Attacks per round, dtype: float64
Min value: 0.008, Max value: 3.04
Unique values: 177

Column: Role Stats_Firepower_Damage per round win
Data type: float64
0    108.2
1     86.4
2     91.6
3    114.8
4     95.8
Name: Role Stats_Firepower_Damage per round win, dtype: float64
Min value: 0.4, Max value: 115.6
Unique values: 383

Column: Role Stats_Sniping_Score
Data type: float64
0    0.86
1    0.87
2    0.93
3    0.01
4    0.91
Name: Role Stats_Sniping_Score, dtype: float64
Min value: 0.0, Max value: 0.96
Unique values: 71

Column: Basic Info_Player Name
Data type: object
0     ZywOo
1    s1mple
2     sh1ro
3      donk
4      deko
Name: Basic Info_Player Name, dtype: object
Unique values: 966

Column: Role Stats_Opening_Opening attempts
Data type: float64
0    0.223
1    0.202
2    0.131
3    0.272
4    0.129
Name: Role Stats_Opening_Opening attempts, dtype: float64
Min value: 0.11699999999999999, Max value: 0.344
Unique values: 176

Column: Role Stats_Utility_Score
Data type: float64
0    0.61
1    0.37
2    0.66
3    0.28
4    0.58
Name: Role Stats_Utility_Score, dtype: float64
Min value: 0.08, Max value: 0.95
Unique values: 84

Column: Role Stats_Clutching_Time alive per round
Data type: object
0    1m 10s
1    0m 59s
2    1m 19s
3     1m 6s
4    1m 20s
Name: Role Stats_Clutching_Time alive per round, dtype: object
Unique values: 89

Column: Detailed Stats_Rounds played
Data type: int64
0    34629
1    45750
2    31066
3    11601
4    23640
Name: Detailed Stats_Rounds played, dtype: int64
Min value: 10785, Max value: 67615
Unique values: 955

Column: Role Stats_Sniping_Sniper opening kills per round
Data type: float64
0    0.0300
1    0.0300
2    0.0400
3    0.0002
4    0.0300
Name: Role Stats_Sniping_Sniper opening kills per round, dtype: float64
Min value: 0.0, Max value: 0.08
Unique values: 27

Column: Detailed Stats_Grenade dmg / Round
Data type: float64
0    3.7
1    2.5
2    3.9
3    3.6
4    4.1
Name: Detailed Stats_Grenade dmg / Round, dtype: float64
Min value: 1.3, Max value: 9.5
Unique values: 69

Column: Role Stats_Clutching_Last alive percentage
Data type: float64
0    0.125
1    0.124
2    0.178
3    0.069
4    0.171
Name: Role Stats_Clutching_Last alive percentage, dtype: float64
Min value: 0.0, Max value: 0.20800000000000002
Unique values: 141

Column: Detailed Stats_Maps played
Data type: int64
0    1334
1    1727
2    1189
3     468
4     927
Name: Detailed Stats_Maps played, dtype: int64
Min value: 451, Max value: 2610
Unique values: 662

Column: Role Stats_Trading_Saved teammate per round
Data type: float64
0    0.15
1    0.10
2    0.13
3    0.18
4    0.12
Name: Role Stats_Trading_Saved teammate per round, dtype: float64
Min value: 0.0, Max value: 0.18
Unique values: 18

Column: Summary Stats_Rating 2.0
Data type: float64
0    1.32
1     NaN
2    1.25
3    1.27
4    1.22
Name: Summary Stats_Rating 2.0, dtype: float64
Min value: 0.9, Max value: 1.32
Unique values: 37

Column: Role Stats_Opening_Score
Data type: float64
0    0.89
1    0.87
2    0.60
3    0.86
4    0.54
Name: Role Stats_Opening_Score, dtype: float64
Min value: 0.14, Max value: 0.91
Unique values: 78

Column: Role Stats_Entrying_Traded deaths percentage
Data type: float64
0    0.225
1    0.135
2    0.178
3    0.229
4    0.184
Name: Role Stats_Entrying_Traded deaths percentage, dtype: float64
Min value: 0.001, Max value: 0.284
Unique values: 169

In [16]:
# List of columns that were missed in the previous conversion
missed_columns = [
    'Role Stats_Trading_Assisted kills percentage',#0    16.1%
    'Role Stats_Firepower_Pistol round rating', #0    1.42
    'Role Stats_Clutching_Time alive per round', #0    1m 10s
]

def convert_percentage(value):
    if isinstance(value, str) and value.endswith('%'):
        return float(value.rstrip('%')) / 100
    return value

def convert_rating(value):
    if isinstance(value, str):
        if value == '-':
            return np.nan
        else:
            return float(value)
    return value

def convert_time(value):
    if isinstance(value, str):
        parts = value.split()
        minutes = int(parts[0].rstrip('m'))
        seconds = int(parts[1].rstrip('s'))
        return minutes * 60 + seconds  # Convert to total seconds
    return value

# Convert the missed columns
for col in missed_columns:
    if col in df.columns:
        print(f"Converting column: {col}")
        if 'percentage' in col.lower():
            df[col] = df[col].apply(convert_percentage)
        elif 'rating' in col.lower():
            df[col] = df[col].apply(convert_rating)
        elif 'time' in col.lower():
            df[col] = df[col].apply(convert_time)
        
        print(f"New data type: {df[col].dtype}")
        print(df[col].head())
        print(f"Min value: {df[col].min()}, Max value: {df[col].max()}")
        print(f"Unique values: {df[col].nunique()}\n")
    else:
        print(f"Column not found: {col}\n")

Converting column: Role Stats_Trading_Assisted kills percentage
New data type: float64
0    0.161
1    0.081
2    0.100
3    0.181
4    0.077
Name: Role Stats_Trading_Assisted kills percentage, dtype: float64
Min value: -0.128, Max value: 0.259
Unique values: 228

Converting column: Role Stats_Firepower_Pistol round rating
New data type: float64
0    1.42
1     NaN
2    1.33
3    1.42
4    1.23
Name: Role Stats_Firepower_Pistol round rating, dtype: float64
Min value: 0.8, Max value: 1.42
Unique values: 59

Converting column: Role Stats_Clutching_Time alive per round
New data type: int64
0    70
1    59
2    79
3    66
4    80
Name: Role Stats_Clutching_Time alive per round, dtype: int64
Min value: -193652, Max value: 2380
Unique values: 89

In [17]:
# Check for remaining object columns
object_columns = df.select_dtypes(include=['object']).columns
if not object_columns.empty:
    print("\nRemaining object columns:")
    print(object_columns.tolist())
else:
    print("\nNo remaining object columns.")

Remaining object columns:
['Basic Info_Team Name', 'Basic Info_Real Name', 'Basic Info_Player Name']

### Step 3: Handling NaN Values and Dropping Unnecessary Columns

After converting all relevant columns to numeric data types (either `float` or `int`), we are left with only the necessary non-numeric columns, such as player names and team names, which remain as `object` types.

*Note: The `URL` column was dropped earlier to simplify the conversion process, as it was not needed for the analysis.*

In this step, we will:
1. **Check for NaN or missing values**: It’s important to ensure there are no missing values in the key columns, such as player statistics or team names, which could negatively impact our analysis.
2. **Evaluate and drop unnecessary columns**: We will review the remaining columns to identify any that are not useful for analysis, such as redundant or irrelevant fields, and remove them from the dataset to streamline our work.

By cleaning up the dataset, we will ensure it is ready for further analysis, and we can proceed with normalizing the data and performing team-based breakdowns.

In [18]:
# Function to calculate the percentage of missing values
def missing_percentage(column):
    return (column.isnull().sum() / len(column)) * 100

# Create a summary of missing values
missing_summary = df.apply(missing_percentage).sort_values(ascending=False)

# Filter columns with missing values
columns_with_missing = missing_summary[missing_summary > 0]

if not columns_with_missing.empty:
    print("Columns with missing values:")
    for column, percentage in columns_with_missing.items():
        print(f"{column}: {percentage:.2f}% missing")
else:
    print("No columns with missing values found.")

Columns with missing values:
Detailed Stats_Rating 1.0: 57.44% missing
Summary Stats_Rating 1.0: 57.44% missing
Detailed Stats_Rating 2.0: 42.56% missing
Role Stats_Firepower_Rating 2.0: 42.56% missing
Summary Stats_Rating 2.0: 42.56% missing
Role Stats_Firepower_Pistol round rating: 42.56% missing

In [19]:
# Check for any remaining non-numeric values that might have been converted to NaN
def check_nan_values(column):
    return column.isnull().sum() if column.dtype in ['float64', 'int64'] else 0

non_numeric_summary = df.apply(check_nan_values)
non_numeric_columns = non_numeric_summary[non_numeric_summary > 0]

if not non_numeric_columns.empty:
    print("\nNumeric columns with NaN values:")
    for column, count in non_numeric_columns.items():
        print(f"{column}: {count} NaN values")
else:
    print("\nNo numeric columns with NaN values found.")

Numeric columns with NaN values:
Detailed Stats_Rating 1.0: 556 NaN values
Role Stats_Firepower_Rating 2.0: 412 NaN values
Detailed Stats_Rating 2.0: 412 NaN values
Summary Stats_Rating 1.0: 556 NaN values
Role Stats_Firepower_Pistol round rating: 412 NaN values
Summary Stats_Rating 2.0: 412 NaN values

In [20]:
# Suggestion for handling missing values
print("\nSuggestions for handling missing values:")
for column, percentage in columns_with_missing.items():
    if percentage < 5:
        print(f"- {column}: Consider imputing missing values (e.g., mean, median, or mode).")
    elif 5 <= percentage < 20:
        print(f"- {column}: Investigate the reason for missing data. Consider advanced imputation techniques or feature engineering.")
    else:
        print(f"- {column}: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.")

Suggestions for handling missing values:
- Detailed Stats_Rating 1.0: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.
- Summary Stats_Rating 1.0: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.
- Detailed Stats_Rating 2.0: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.
- Role Stats_Firepower_Rating 2.0: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.
- Summary Stats_Rating 2.0: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.
- Role Stats_Firepower_Pistol round rating: High percentage of missing data. Consider dropping this column or using it to create a binary 'is_missing' feature.

In [21]:
def find_player_with_nan_ratings(df):
    """
    Find and display a player with NaN rating in the 'Summary Stats_Rating 2.0' column.
    
    :param df: pandas DataFrame
    :return: None (prints information)
    """
    # Specify the column we're interested in
    target_column = 'Summary Stats_Rating 2.0'
    
    # Find rows where the target column is NaN
    players_with_nan = df[df[target_column].isna()]
    
    if players_with_nan.empty:
        print(f"No players found with NaN ratings in the '{target_column}' column.")
        return
    
    # Select the first player with NaN rating
    player = players_with_nan.iloc[0]
    
    print(f"Player found with NaN rating in '{target_column}':")
    print(f"Name: {player['Basic Info_Player Name']}")
    print(f"Team: {player['Basic Info_Team Name']}")
    print(f"\n{target_column}: NaN")
    
    print("\nFull Player Information:")
    for col, value in player.items():
        print(f"{col}: {value}")

find_player_with_nan_ratings(df)

Player found with NaN rating in 'Summary Stats_Rating 2.0':
Name: s1mple
Team: Natus Vincere

Summary Stats_Rating 2.0: NaN

Full Player Information:
Summary Stats_DPR: 0.63
Summary Stats_KPR: 0.85
Detailed Stats_Deaths / round: 0.63
Role Stats_Firepower_Score: 0.97
Role Stats_Opening_Win% after opening kill: 0.7559999999999999
Role Stats_Clutching_Score: 0.52
Detailed Stats_Damage / Round: 85.4
Detailed Stats_Headshot %: 0.41100000000000003
Role Stats_Opening_Opening deaths per round: 0.09
Role Stats_Entrying_Support rounds: 0.105
Basic Info_Team Name: Natus Vincere
Role Stats_Sniping_Rounds with sniper kills percentage: 0.155
Detailed Stats_Assists / round: 0.1
Role Stats_Sniping_Sniper kills per round: 0.18
Role Stats_Opening_Opening kills per round: 0.11
Role Stats_Sniping_Sniper multi-kill rounds: 0.05
Detailed Stats_Kills / round: 0.85
Detailed Stats_Rating 1.0: 1.24
Role Stats_Firepower_Rating 2.0: nan
Role Stats_Opening_Opening success: 0.5529999999999999
Detailed Stats_Total kills: 38714
Role Stats_Firepower_Rounds with a kill: 0.518
Detailed Stats_Rating 2.0: nan
Role Stats_Firepower_Rounds with a multi-kill: 0.21
Detailed Stats_Total deaths: 29045
Role Stats_Entrying_Score: 0.06
Role Stats_Clutching_Clutch points per round: 0.03
Basic Info_Age: 23
Role Stats_Trading_Trade kills percentage: 0.17600000000000002
Role Stats_Clutching_Saves per round loss: 0.038
Role Stats_Entrying_Saved by teammate per round: 0.07
Role Stats_Trading_Score: 0.26
Role Stats_Utility_Utility kills per 100 rounds: 0.4
Summary Stats_Impact: 1.34
Role Stats_Entrying_Opening deaths traded percentage: 0.135
Role Stats_Utility_Flashes thrown per round: 0.73
Summary Stats_KAST: 0.7390000000000001
Role Stats_Firepower_Kills per round: 0.8
Role Stats_Trading_Assisted kills percentage: 0.081
Detailed Stats_Saved by teammate / round: 0.08
Role Stats_Entrying_Traded deaths per round: 0.09
Role Stats_Entrying_Assists per round: 0.09
Role Stats_Trading_Trade kills per round: 0.14
Role Stats_Trading_Damage per kill: 80
Role Stats_Utility_Flash assists per round: 0.04
Role Stats_Utility_Time opponent flashed per round: 1.96
Summary Stats_Rating 1.0: 1.24
Basic Info_Real Name: Oleksandr Kostyliev
Summary Stats_ADR: 85.4
Role Stats_Clutching_1on1 win percentage: 0.706
Role Stats_Utility_Utility damage per round: 1.74
Role Stats_Firepower_Pistol round rating: nan
Detailed Stats_Saved teammates / round: 0.11
Role Stats_Firepower_Damage per round: 81.8
Detailed Stats_K/D Ratio: 1.33
Role Stats_Sniping_Sniper kills percentage: 0.28800000000000003
Role Stats_Firepower_Kills per round win: 1.09
Role Stats_Opening_Attacks per round: 1.66
Role Stats_Firepower_Damage per round win: 86.4
Role Stats_Sniping_Score: 0.87
Basic Info_Player Name: s1mple
Role Stats_Opening_Opening attempts: 0.20199999999999999
Role Stats_Utility_Score: 0.37
Role Stats_Clutching_Time alive per round: 59
Detailed Stats_Rounds played: 45750
Role Stats_Sniping_Sniper opening kills per round: 0.03
Detailed Stats_Grenade dmg / Round: 2.5
Role Stats_Clutching_Last alive percentage: 0.124
Detailed Stats_Maps played: 1727
Role Stats_Trading_Saved teammate per round: 0.1
Summary Stats_Rating 2.0: nan
Role Stats_Opening_Score: 0.87
Role Stats_Entrying_Traded deaths percentage: 0.135

In [22]:
# Removing duplicate colums
columns_to_drop = [
    'Role Stats_Firepower_Rating 2.0',
    'Detailed Stats_Rating 1.0',
    'Detailed Stats_Rating 2.0',
    'Role Stats_Firepower_Pistol round rating'
]

df = df.drop(columns=columns_to_drop)
print(f"Dropped columns: {columns_to_drop}")

Dropped columns: ['Role Stats_Firepower_Rating 2.0', 'Detailed Stats_Rating 1.0', 'Detailed Stats_Rating 2.0', 'Role Stats_Firepower_Pistol round rating']

In [23]:
# Combine the two rating columns (1.0 and 2.0) into a single column
df['Summary Stats_Rating'] = df['Summary Stats_Rating 1.0'].fillna(df['Summary Stats_Rating 2.0'])

# Create a binary indicator for missing ratings
df['Summary Stats_Rating_is_missing'] = df['Summary Stats_Rating'].isna().astype(int)

# Drop the original separate rating columns
df = df.drop(columns=['Summary Stats_Rating 1.0', 'Summary Stats_Rating 2.0'])

# Verify the changes
print("\nColumn names after changes:")
print(df.columns.tolist())

print("\nSummary of the combined rating column:")
print(df[['Summary Stats_Rating', 'Summary Stats_Rating_is_missing']].describe())

print("\nCheck for any remaining NaN values in the rating column:")
print(df['Summary Stats_Rating'].isna().sum())

print("\nSample of the updated data:")
print(df[['Summary Stats_Rating', 'Summary Stats_Rating_is_missing']].head())

Column names after changes:
['Summary Stats_DPR', 'Summary Stats_KPR', 'Detailed Stats_Deaths / round', 'Role Stats_Firepower_Score', 'Role Stats_Opening_Win% after opening kill', 'Role Stats_Clutching_Score', 'Detailed Stats_Damage / Round', 'Detailed Stats_Headshot %', 'Role Stats_Opening_Opening deaths per round', 'Role Stats_Entrying_Support rounds', 'Basic Info_Team Name', 'Role Stats_Sniping_Rounds with sniper kills percentage', 'Detailed Stats_Assists / round', 'Role Stats_Sniping_Sniper kills per round', 'Role Stats_Opening_Opening kills per round', 'Role Stats_Sniping_Sniper multi-kill rounds', 'Detailed Stats_Kills / round', 'Role Stats_Opening_Opening success', 'Detailed Stats_Total kills', 'Role Stats_Firepower_Rounds with a kill', 'Role Stats_Firepower_Rounds with a multi-kill', 'Detailed Stats_Total deaths', 'Role Stats_Entrying_Score', 'Role Stats_Clutching_Clutch points per round', 'Basic Info_Age', 'Role Stats_Trading_Trade kills percentage', 'Role Stats_Clutching_Saves per round loss', 'Role Stats_Entrying_Saved by teammate per round', 'Role Stats_Trading_Score', 'Role Stats_Utility_Utility kills per 100 rounds', 'Summary Stats_Impact', 'Role Stats_Entrying_Opening deaths traded percentage', 'Role Stats_Utility_Flashes thrown per round', 'Summary Stats_KAST', 'Role Stats_Firepower_Kills per round', 'Role Stats_Trading_Assisted kills percentage', 'Detailed Stats_Saved by teammate / round', 'Role Stats_Entrying_Traded deaths per round', 'Role Stats_Entrying_Assists per round', 'Role Stats_Trading_Trade kills per round', 'Role Stats_Trading_Damage per kill', 'Role Stats_Utility_Flash assists per round', 'Role Stats_Utility_Time opponent flashed per round', 'Basic Info_Real Name', 'Summary Stats_ADR', 'Role Stats_Clutching_1on1 win percentage', 'Role Stats_Utility_Utility damage per round', 'Detailed Stats_Saved teammates / round', 'Role Stats_Firepower_Damage per round', 'Detailed Stats_K/D Ratio', 'Role Stats_Sniping_Sniper kills percentage', 'Role Stats_Firepower_Kills per round win', 'Role Stats_Opening_Attacks per round', 'Role Stats_Firepower_Damage per round win', 'Role Stats_Sniping_Score', 'Basic Info_Player Name', 'Role Stats_Opening_Opening attempts', 'Role Stats_Utility_Score', 'Role Stats_Clutching_Time alive per round', 'Detailed Stats_Rounds played', 'Role Stats_Sniping_Sniper opening kills per round', 'Detailed Stats_Grenade dmg / Round', 'Role Stats_Clutching_Last alive percentage', 'Detailed Stats_Maps played', 'Role Stats_Trading_Saved teammate per round', 'Role Stats_Opening_Score', 'Role Stats_Entrying_Traded deaths percentage', 'Summary Stats_Rating', 'Summary Stats_Rating_is_missing']

Summary of the combined rating column:
       Summary Stats_Rating  Summary Stats_Rating_is_missing
count            968.000000                            968.0
mean               1.041746                              0.0
std                0.068933                              0.0
min                0.810000                              0.0
25%                1.000000                              0.0
50%                1.040000                              0.0
75%                1.090000                              0.0
max                1.320000                              0.0

Check for any remaining NaN values in the rating column:
0

Sample of the updated data:
   Summary Stats_Rating  Summary Stats_Rating_is_missing
0                  1.32                                0
1                  1.24                                0
2                  1.25                                0
3                  1.27                                0
4                  1.22                                0

In [24]:
#Check for NaN values across all columns
nan_check = df.isna().sum()

# Filter to show only columns with NaN values
columns_with_nan = nan_check[nan_check > 0]

if columns_with_nan.empty:
    print("Great news! There are no NaN values in any column of the DataFrame.")
else:
    print("The following columns contain NaN values:")
    print(columns_with_nan)

Great news! There are no NaN values in any column of the DataFrame.

### Step 4: Final Data Preparation and Team-Based Breakdown

With all NaN values successfully addressed and only the relevant object values (such as player names and team names) remaining in our dataset, we are now ready to move on to the next phase of our analysis.

In this step, we will:
1. **Normalize Player Statistics**: To ensure consistency across all teams, we will normalize the numerical columns, such as player statistics, to prepare the data for meaningful comparisons.
2. **Create Team-Specific DataFrames**: Once the data is normalized, we will create separate DataFrames for each team, allowing us to easily focus on team-specific player data and conduct more targeted analysis.

This step will finalize our dataset, making it well-structured and ready for further analysis or modeling.